env:
  global:
    - CC_TEST_REPORTER_ID=1e3ec5811ac302fdb07f45ebaaf056eb3e9d673bbc0e0b7b3891730d9831b427
language: php
php:
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - composer install --prefer-dist --no-interaction
  - vendor/bin/phpunit tests/ $PHPUNIT_FLAGS --configuration travis.phpunit.xml
after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi